version: '3'
services:
  spring-boot-server:
    build:
      context: ./server/url-shortener
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - redis-server
      - mongo-server
      - zookeeper-server
    networks:
      - url-shortener-network
    restart: always

  client-server:
    build:
      context: ./client/url-shortener
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - url-shortener-network
    restart: always

  redis-server:
    image: redis
    container_name: redis-server
    command: redis-server --bind 0.0.0.0
    ports:
      - '6379:6379'
    networks:
      - url-shortener-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper-server:
    image: zookeeper
    container_name: zookeeper-server
    ports:
      - '2181:2181'
    networks:
      - url-shortener-network
    restart: always

  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    networks:
      - url-shortener-network
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-boot-server
    ports:
      - '4000:80'
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge